### ISSUE TITLE
Misalignment for lists within blockquotes

### ISSUE THREAD

**Issue by davidbgk** [fvsch/remarkdown#7]
I think I found a minor bug when a blockquote contains a list, here is from the default CSS:

<img width="1113" alt="Capture d’écran, le 2021-02-03 à 20 26 32" src="https://user-images.githubusercontent.com/3556/106831593-2c3baf00-665e-11eb-9c0f-ff18bacd0bba.png">

And here with my fix applied (bigger margin-top):

<img width="1055" alt="Capture d’écran, le 2021-02-03 à 20 26 47" src="https://user-images.githubusercontent.com/3556/106831608-3067cc80-665e-11eb-9fbb-fa79a637bf05.png">

I tried with another font and it doesn't look to be specific to the one I use. I can provide a patch if you confirm/reproduce.

**Comment by davidbgk** [comment]
Mmmh not so fast, there is probably a compromise to find between the alignment of the star (bullet point) and the one of the text itself. `1.6em` is probably a better value to set.

**Comment by fvsch** [comment]
So `1.5em` comes from the default value for the `$rmd-line-ratio` variable set in https://github.com/fvsch/remarkdown/blob/main/src/_options.scss, which results in styles such as:

- `line-height: 1.5`
- `margin-top: 1.5em`

Keeping `1.5em` here is important so that the text in the list items aligns with the `>` signs from the blockquote decorations.

The main issue is that the characters `>*` are not vertically aligned in most fonts.

If you’re using a font which has a specific stylistic alternate to make the `*` characters aligned with the middle of x-heights, like some coding fonts, you could use `font-feature-settings` in CSS to trigger that alternate for all `*` characters, or targeting only pseudo-elements or the `::before` pseudo-elements used by lists.
https://wakamaifondue.com/beta/ is a good tool to see what a font supports.

Or you could nudge it down a bit in CSS. I’m getting decent results with:

```css
.remarkdown.ul-star ul > li::before {
  position: relative;
  top: 0.15em;
}
```

Alternatively, you may want to try a different character altogether, maybe:
- ASTERISK OPERATOR U+2217 https://www.fileformat.info/info/unicode/char/2217/index.htm
- FULLWIDTH ASTERISK U+FF0A https://www.fileformat.info/info/unicode/char/ff0a/index.htm

**Comment by davidbgk** [comment]
Thanks a lot for your feedback, I learned a lot of things! 🙇 

I eventually did what you recommend with:

```css
.remarkdown.ul-star ul > li::before,
.remarkdown strong::before,
.remarkdown strong::after {
  position: relative;
  top: 0.15em;
}
```

This way I have both the blockquote almost aligned and in case of bold elements it's closer to the baseline (which I prefer).

<img width="768" alt="Capture d’écran, le 2021-03-01 à 21 16 34" src="https://user-images.githubusercontent.com/3556/109586576-71bf9080-7ad3-11eb-8da3-a0a5e33f6539.png">

Different characters were not pertinent with the font I use.
