### ISSUE TITLE
Headings have no effects on font size

### ISSUE THREAD

**Issue by ijunaid8989** [fvsch/remarkdown#8]
Thanks for this library it's really great to use.

I am having a few issues. I am trying to use headings such as 

# Hello
### Hello

but When I do while using this library it has 0 effects. every Heading is of the same size.

also, I want to use the quotes as 

> Hello I am a quote

It gives something different.

You can see this link for the reference 

https://ijunaidfarooq.com/2021/06/21/something-about-pakistan/

the repository is this one https://github.com/ijunaid8989/ijunaid8989.github.io

**Comment by fvsch** [comment]
The default build of ReMarkdown does reset the font-size of headings, and that's by design. It's meant to mimic the look of plain markdown text.

Looking at your link, it looks like you’re using the ReMarkdown-zero build, which doesn't reset the font-size of headings, but provides a `hn-reset` option that can be used as:

```html
<element class="remarkdown hn-reset">...</element>
```

And it also looks like you're using this option class. If you don't want this effect, you could remove it.

I’m also seeing that you have some style overrides in a file named `styles.css`, but you include it _before_ `remarkdown.css`, so even when the [selector specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) is the same the styles in `remarkdown.css` will overrides your styles from `styles.css`:

```html
  <link rel="stylesheet" href="/assets/css/styles.css">
  <link rel="stylesheet" href="/assets/css/remarkdown.css">
```

So I would advise inverting the order of those two lines, and not using the `hn-reset` class.
